FROM centos:8

RUN yum install -y git cmake gcc gcc-c++ make epel-release

RUN yum install -y openssl-devel boost-devel

COPY . /workspace

WORKDIR /workspace

RUN git submodule update --init && git -C vendor/cpprestsdk submodule update --init

RUN mkdir -p build && cd build && cmake ../

RUN make -j 2 -C build/ && make -j 2 -C build/ test
